export default {
    "events": [
        {
            "created": 1460672343000,
            "id": "tqvmslyvqbxb",
            "name": "bicycle workshop",
            "status": "upcoming",
            "time": 1482084000000,
            "updated": 1460672343000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 2,
            "venue": {
                "id": 13933482,
                "name": "TAMI",
                "lat": 32.171016693115234,
                "lon": 34.85884094238281,
                "repinned": false,
                "address_1": "Kibbutz Galuyot 45",
                "address_2": "Studio #106, 3rd Floor ",
                "city": "Tel Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1380728634000,
                "name": "Tel Aviv Makers (TAMI)",
                "id": 10521552,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Tel-Aviv-Makers-TAMI",
                "who": "Hackers"
            },
            "link": "https://www.meetup.com/Tel-Aviv-Makers-TAMI/events/236143188/",
            "description": "<p>We will try to  learn how to fix a bicycle.<br/>You may bring along the bike or a wheel and we can tackle it together.<br/>The idea is to try to rebuild or fix the old parts and re-use them, whenever possible.<br/>There are tools, support and very few parts at the space.</p> ",
            "visibility": "public"
        },
        {
            "created": 1479111780000,
            "duration": 119700000,
            "id": "235568755",
            "name": "OH-MAN, OH-MACHINE 2016",
            "status": "upcoming",
            "time": 1482132600000,
            "updated": 1479117455000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 19,
            "venue": {
                "id": 24899751,
                "name": "Room 496, Gilman building, 4th floor",
                "lat": 32.103633880615234,
                "lon": 34.804603576660156,
                "repinned": false,
                "address_1": "Tel Aviv University",
                "city": "Tel Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1459262789000,
                "name": "Ethical Legal and Social Implications of Emerging Tech",
                "id": 19772858,
                "join_mode": "open",
                "lat": 32.16999816894531,
                "lon": 34.84000015258789,
                "urlname": "Ethical-Legal-and-Social-Implications-of-Emerging-Tech",
                "who": "Members"
            },
            "link": "https://www.meetup.com/Ethical-Legal-and-Social-Implications-of-Emerging-Tech/events/235568755/",
            "description": "<p>Questions concerning Technology and Biology</p> <p>In which arenas are biology &amp; technology cooperating, complementing each other, coevolving and possibly merging, and in which are they competing, merely mimicking one another, or pulling towards different ends? What sort of boundary work between the made and the born is involved in these processes? Each panel engages a different type of relationship between biology and technology that is addressed by the multiple perspectives of science,humanities, and the arts.</p> <p>\n\n\n<img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/a/4/1/600_456062625.jpeg\" /></p> <p><b>December 19 (Monday)</b></p> <p><br/><b>9:30-10:00 Opening</b><br/>Leo Corry, Dean of Humanities, Tel Aviv University<br/>Jose Brunner, Director, Cohn institute, Tel Aviv University</p> <p><br/><b>10:00-12:00 Origins</b><br/>Moshe Kol, Tel Aviv University<br/>Evolution of Alternative Life Forms from an Inorganic/Organic Chemist\u2019s Perspective</p> <p>Raz Chen-Morris, The Hebrew University of Jerusalem<br/>The Eye as an Organ and Instrument in Early Modern Europe</p> <p><br/>Elana Gomel, Tel Aviv University<br/>Biological Sublime: Biology, Technology, Science Fiction</p> <p><br/>Chair/commentator: Eran Hadas, poet, software developer, and new media artist</p> <p><b>12:00-13:00 Lunch</b></p> <p><br/><b>13:00-15:00 The Anthropocene: Mimicry and Beyond</b></p> <p><br/>Dana Zelig, Bezalel Academy of Arts and Design<br/>Growing Patterns</p> <p><br/>Yoram Reich, Tel Aviv University<br/>Designing a Dialogue between the Natural and the Artificial:What is the Purpose?</p> <p>Pieter Lemmens, Radboud University Nijmegen, The Netherlands Reflections on Digital Technology and Intelligence in the Anthropocene</p> <p><br/>Chair/commentator: Daniel Mishori, Tel Aviv University</p> <p><br/><b>15:00-15:30 Coffee break</b></p> <p><br/><b>15:30-17:30 Biology as Technology</b><br/>Ehud Shapiro, Weizmann Institute of Science<br/>Programming Languages for Life</p> <p>Christopher Coenen, Karlsruhe Institute of Technology, Germany Programmable Matter</p> <p><br/>Denisa Kera, Charles University, Prague, Czech Republic<br/>Tinkering with the Blockchain: Ontogeny and Phylogeny of Networks</p> <p><br/>Chair/commentator: Doron Friedman, IDC Herzliya</p> <p><br/><b>17:30-18:00 Coffee break</b></p> <p><br/><b>18:00-19:30 Keynote</b><br/>Peter-Paul Verbeek, Twente University, The Netherlands<br/>Sapiens ex Machina: Towards an Anthropology of Human-Robot Relations</p> <p>\n\n\n\n<b>December 20 (Tuesday)</b></p> <p><br/><b>9:00-11:00 The Technologization of Biology</b></p> <p><br/>Noam Shomron, Tel Aviv University<br/>The Human Genome Revolution</p> <p><br/>Tamar Sharon, Maastricht University, The Netherlands The  Googlization of Medicine</p> <p><br/>Nurit Bar Shai, artist<br/>Artists and Citizen Scientists at the Forefront of Biotechnology</p> <p><br/>Chair/commentator: Snait Gissis, Tel Aviv University</p> <p><br/><b>11:00-11:30 Coffee break</b></p> <p><br/><b>11:30-13:30 Cyborg 1: Between Disability and Enhancement</b></p> <p><br/>Iddo Gruengard, multidisciplinary artist<br/>The Void between Technology and the Body</p> <p><br/>Amir Amedi, The Hebrew University of Jerusalem<br/>Challenges and Opportunities in using Brain Implants and what it teaches us about the Brain</p> <p>Dov Greenbaum, Yale University &amp; IDC Herzliya<br/>When Disabilities are Desired Abilities</p> <p><br/>Chair/commentator: Carmel Vaisman, Tel Aviv University<b><br/></b></p> <p><b>13:30-14:30 Lunch break</b></p> <p><b>14:30-16:30 Cyborg 2: Synergy in Virtual/Augmented Reality</b></p> <p>Galit Wellner, The NB School of Design &amp; Tel Aviv University<br/>Postphenomenology of AR</p> <p><br/>Daniel Landau, Aalto University, Finland<br/>Narrative and Re-embodiment in Virtual Reality</p> <p><br/>Miriam Reiner, Technion-Israeli Institute of Technology<br/>The Synergetic Process of Virtual/Augmented Reality and Enhanced Human Cognition: Two Examples</p> <p>Chair/commentator: Nea Erlich, Van Leer Institute</p> <p><br/><b>16:30-17:00 Coffee break<br/>17:00-17:15 Continuing the dialogue: upcoming events<br/></b></p> <p>Carmel Vaisman, Tel Aviv University</p> <p><br/>Lior Zalmanson, New York University &amp; Print Screen Festival</p> <p><br/><b>17:15-19:15 Back to the Future</b><br/>Ehud Gazit, Tel Aviv University<br/>Molecular Self-Organization: From the Origin of Life to 21st Century Technology</p> <p>Oron Catts, The University of Western Australia<br/>Growing the Made: The Industrialization of Biology vs. the Biologization of Industry - A Cultural Perspective</p> <p>Ehud Lamm, Tel Aviv University<br/>Why Biologists Didn't like Math? Or, is it Time for a New Macy Conference?</p> <p><br/>Chair/commentator: Keren Omry, University of Haifa</p> ",
            "visibility": "public"
        },
        {
            "created": 1380812424000,
            "id": "dxtgwgyvqbzb",
            "name": "autoscheduled test",
            "status": "upcoming",
            "time": 1482179400000,
            "updated": 1380812424000,
            "utc_offset": -18000000,
            "waitlist_count": 0,
            "yes_rsvp_count": 2,
            "venue": {
                "id": 1543700,
                "name": "632 Broadway, New York, NY 10012",
                "lat": 40.72602462768555,
                "lon": -73.99617767333984,
                "repinned": false,
                "address_1": "632 Broadway, New York, NY 10012",
                "city": "New York",
                "country": "us",
                "localized_country_name": "USA",
                "zip": "10012",
                "state": "Ne"
            },
            "group": {
                "created": 1258123610000,
                "name": "Meetup API Testing Sandbox",
                "id": 1556336,
                "join_mode": "open",
                "lat": 40.70000076293945,
                "lon": -73.98999786376953,
                "urlname": "Meetup-API-Testing",
                "who": "Developers"
            },
            "link": "https://www.meetup.com/Meetup-API-Testing/events/229400621/",
            "manual_attendance_count": 0,
            "description": "<p>testing autoscheduled event</p> ",
            "visibility": "public_limited"
        },
        {
            "created": 1480541221000,
            "duration": 3600000,
            "id": "235940120",
            "name": "Deep dive of deduplication using Apache Apex and RTS",
            "status": "upcoming",
            "time": 1482156000000,
            "updated": 1480541233000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 16,
            "venue": {
                "id": 24842033,
                "name": "Webcast",
                "lat": 32.08530044555664,
                "lon": 34.781768798828125,
                "repinned": false,
                "address_1": "Online",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1475691680000,
                "name": "Big Data Hadoop Ingest Transform Apex Tel-Aviv Online",
                "id": 20614288,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Big-Data-Hadoop-Ingest-Transform-Apex-Tel-Aviv-Online",
                "who": "Members"
            },
            "link": "https://www.meetup.com/Big-Data-Hadoop-Ingest-Transform-Apex-Tel-Aviv-Online/events/235940120/",
            "manual_attendance_count": 0,
            "description": "<p>Presenter: Bhupesh Chawda, Engineer at DataTorrent and Committer at Apache Apex.</p> <p>Abstract: This webinar will introduce the De-duplication functionality in Malhar. De-duplication is a very important part of the processing pipeline in ETL workflows. We will introduce the use cases and walk through the implementation details. Next we'll look at how to configure the Dedup operator for various use cases (time based expiry as well as batch de-duplication). We will also get into a demonstration of an application which uses De-duplication (Dedup) operator.</p> <p>Bio: Bhupesh Chadwa is a Software Engineer at DataTorrent and Committer for Apache Apex.</p> <p>Please register for the webinar at: <a href=\"https://attendee.gotowebinar.com/register/6110313049520480515\" class=\"linkified\">https://attendee.gotowebinar.com/register/6110313049520480515</a></p> <p>After registering, you will receive a confirmation email containing information about joining the webinar.</p> <p>For deeper engagement with <a href=\"http://apex.apache.org/\">Apache Apex</a>, <a href=\"https://www.datatorrent.com/download/?utm_source=meetup&amp;utm_medium=meetup_links&amp;utm_campaign=links_in_description\">download</a>, view past <a href=\"https://www.datatorrent.com/webinars/?utm_source=meetup&amp;utm_medium=meetup_links&amp;utm_campaign=links_in_description\">meetup webinars</a>, <a href=\"http://www.slideshare.net/DataTorrent\">slides</a>, and <a href=\"http://docs.datatorrent.com/?utm_source=meetup&amp;utm_medium=meetup_links&amp;utm_campaign=links_in_description\">docs</a>.</p> <p>To reduce time to market, look at operable <a href=\"https://www.datatorrent.com/apphub/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">app-templates</a> that you can quickly import and launch. </p> <p>Examples: <a href=\"https://www.datatorrent.com/apphub/hdfs-sync/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">HDFS-Sync</a>, <a href=\"https://www.datatorrent.com/apphub/kafka-to-hdfs-sync/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">Kafka-HDFS</a>, <a href=\"https://www.datatorrent.com/apphub/hdfs-to-hdfs-line-copy/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">HDFS-Line-Copy</a>, <a href=\"https://www.datatorrent.com/apphub/s3-to-hdfs-sync/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">S3-HDFS</a> and <a href=\"https://www.datatorrent.com/apphub/hdfs-to-kafka-sync/?utm_source=meetup&amp;utm_campaign=links_in_description&amp;utm_medium=meetup_links\">HDFS-Kafka</a>.</p> ",
            "visibility": "public"
        },
        {
            "created": 1479884922000,
            "duration": 9000000,
            "id": "235774321",
            "name": "Modern Microservices Architecture using Docker",
            "status": "upcoming",
            "time": 1482159600000,
            "updated": 1481018496000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 141,
            "venue": {
                "id": 24934536,
                "name": "Microsoft R&D, Academy Room, Building 6, L1 Floor",
                "lat": 32.158145904541016,
                "lon": 34.808555603027344,
                "repinned": false,
                "address_1": "Shenkar 13",
                "city": "Herzeliyya",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1429191980000,
                "name": "Azure Israel",
                "id": 18550318,
                "join_mode": "open",
                "lat": 32.16999816894531,
                "lon": 34.84000015258789,
                "urlname": "AzureIsrael",
                "who": "Members"
            },
            "link": "https://www.meetup.com/AzureIsrael/events/235774321/",
            "description": "<p>Microservices are all the rage these days. Docker is a tool which makes managing Microservices a whole lot easier. But what do Microservices really mean? What are the best practices of composing your application with Microservices? How can you leverage Docker and the public cloud to help you build a more agile DevOps process? How does the Azure Container Service fit in? </p> <p>Join us in order to find out the answers.</p> <p>\n\n\n<i>Agenda:</i></p> <p>17:00-17:30 - Gathering</p> <p>17:30-18:15 - Modern Microservices Architecture (Alon Fliess)</p> <p>18:15-18:30 - Break</p> <p>18:30-19:15 - Docker &amp; Azure Container Service in practice (Eran Stiller)</p> <p>\n\n\n<i>About the speakers:</i></p> <p><b>Alon Fliess</b> - Chief Architect &amp; Co-Founder at CodeValue. A Microsoft MVP &amp; MRD. I have a deep and wide knowledge and experience in Microsoft technologies. I am not just talking about it, I'm living it!</p> <p><br/><b>Eran Stiller</b> - A software architect, consultant, instructor and technology addict. Cloud Division Leader and Co-Founder at CodeValue. Microsoft Azure MVP. I live and breathe technology and software flows through my veins.</p> ",
            "visibility": "public"
        },
        {
            "created": 1480861208000,
            "duration": 5400000,
            "id": "236022476",
            "name": "LivePersonDev: Kubernetes your Tests! Automation with Docker on Google Cloud-GCP",
            "status": "upcoming",
            "time": 1482159600000,
            "updated": 1481027697000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 91,
            "venue": {
                "id": 5180122,
                "name": "LivePerson Office",
                "lat": 32.19804382324219,
                "lon": 34.882423400878906,
                "repinned": false,
                "address_1": "13 Zarhin St. Building B, floor 1.",
                "city": "Ra'anana",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1306841610000,
                "name": "ILTechTalks",
                "id": 1943951,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "ILTechTalks",
                "who": "Members"
            },
            "link": "https://www.meetup.com/ILTechTalks/events/236022476/",
            "description": "<p><img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/4/b/f/4/600_446059444.jpeg\" /></p> <p>In this meetup Arik Lerner, Automation Team Leader, and Waseem Hamshawi, Automation Infra Developer, will present how to build a large scale automated testing platform by leveraging containers orchestration over GCP, with the ability to scale out and provide fast feedback while maintaining a highly reliable test infrastructure. </p> <p><b>What will you learn? </b></p> <p>New approach of managing a scalable testing platform of distributed automated tests with Kubernetes and Docker over Google Cloud Platform. </p> <p><b>Agenda: </b></p> <p>\u2022 GCP and Kubernetes introduction for automated testing </p> <p>\u2022 Traditional Selenium Grid vs Selenium Standalone with        Kubernetes and Docker for Web and Mobile tests </p> <p>\u2022 Distributed and containerized testing environment over container cluster - different use cases </p> <p><a href=\"https://github.com/LivePersonInc/ephemerals\">Ephemerals</a> - \"Short-lived Testing Endpoints\". An Open Source by LivePerson which makes automation testing at large scale like a \"Walk in the park\". <br/>You can download the open source [<a href=\"https://github.com/LivePersonInc/ephemerals\">here</a>]</p> <p>\u2022 Demo </p> <p>\u2022 Q&amp;A</p> <p><b>Schedule: </b></p> <p>17:00-17:30 - Gathering with Food &amp; Beers<br/>17:30 - We're starting</p> <p><b> House Keeping Information: </b></p> <p>- FREE Parking is available in the building and in the outdoor parking lot in front of the gas station</p> <p>- Lecture Language: English </p> <p>- This Meetup will be video recorded </p> <p><i>Join us</i>!</p> <p><img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/4/b/f/5/600_446059445.jpeg\" /></p> ",
            "visibility": "public"
        },
        {
            "created": 1478683347000,
            "id": "235458723",
            "name": "The Smart Home (And How Tomorrow Will Look Like)",
            "status": "upcoming",
            "time": 1482163200000,
            "updated": 1481713115000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 246,
            "venue": {
                "id": 19382932,
                "name": "SOSA",
                "lat": 0.0,
                "lon": 0.0,
                "repinned": false,
                "address_1": "13 Shoken st. 3rd floor right above The Junction",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1296990460000,
                "name": "The Junction",
                "id": 1779112,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "The-Junction",
                "who": "Entrepreneurs"
            },
            "link": "https://www.meetup.com/The-Junction/events/235458723/",
            "description": "<p><b>The Future of Smart Homes</b></p> <p>The Junction and Hybrid are happy to invite you to The Smart Home, where we talk about the future of homes. \"Smart Home\" is the term commonly used to define a residence that has appliances, lighting, heating, air conditioning, TVs, computers, entertainment audio &amp; video systems, security, and camera systems that are capable of communicating with one another and can be controlled remotely by a time schedule, from any room in the home, as well as remotely from any location in the world by phone or internet.</p> <p>Barak Rabinowitz, Managing Partner at F2 Capital, will share his vision about where smart homes are a game-changer. </p> <p>Followed by a panel of investors and startup CEO's, moderated by Barak: </p> <p><b>Oren Aharon</b> - Investments, Samsung Strategy and Innovation.</p> <p><b>Moran Haviv</b> - VP Strategic Initiatives at Sears Israel.</p> <p><b>Rami Khawali</b> - Co-founder, MindoLife.  </p> <p><b>Michael Isakov</b> - CEO, Triple+.</p> <p><b>Eran Levy</b> - Managing Director, Enel Innovation Hub.</p> <p><br/>**Agenda and location**<br/>SOSA - 13 Shocken st. Tel Aviv </p> <p>18:00 Doors open and mingling <br/>18:30 Where smart homes are a game-changer <br/>18:45 Panel <br/>19:30 Mingling again</p> <p>**About Hybrid** <br/>Hybrid promotes startups with one or more Arab, Bedouin or Druze founders through BizDev, networking and free office space around Israel. We're a joint venture between the 8200 Alumni Association and the Nazareth Business Incubator, and we're not for profit. Our work includes a pre-accelerator for early-stage startups, that we launched this May for 7 companies (and will end late September). Outside the accelerator we work with more mature startup to help them reach customers, investors and eventually scale. The startups we work with range extremely in fields, from cyber security, through technologies for traditional industries like inventory counting and construction, to EDI and chip verification. These teams also present a very unique opportunity, as the OCS offers a special program that sponsors seed fundings, as high as 85% of 2M NIS. I'd be happy of course to elaborate more about the program and our vision.\u200b \u200b</p> ",
            "visibility": "public"
        },
        {
            "created": 1479209732000,
            "id": "235594559",
            "name": "Reactive meetup",
            "rsvp_limit": 110,
            "status": "upcoming",
            "time": 1482163200000,
            "updated": 1482068290000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 97,
            "venue": {
                "id": 24568251,
                "name": "Soluto Office",
                "lat": 32.06399154663086,
                "lon": 34.77415084838867,
                "repinned": false,
                "address_1": "39 Rothschild Blvd.",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1459336831000,
                "name": "Reactive Extensions (Rx) Israel",
                "id": 19776692,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Reactive-Extensions-Rx-Israel",
                "who": "Observers"
            },
            "link": "https://www.meetup.com/Reactive-Extensions-Rx-Israel/events/235594559/",
            "description": "<p>Rx-Israel 2nd meetup!<br/>Quite some time has passed from our last meetup, like before, we are going to have a few talks on Rx and other \"reactive\" related topics.<br/>Our talks are a bit more advanced then our last meetup, so it's recommended to have some basic familiarity/experience with Rx. </p> <p><b>Agenda </b></p> <p>17:50 - <b>Gathering </b></p> <p>18:10 - <b>Re-implementing observable from scratch<br/>(by Aviv Rozenboim) </b></p> <p>Dive into Observables, and discover how a few simple, easily understandable functions are composed to create an Observable, and gain a better understanding of what happens behind the scenes in an Observable.</p> <p>18:40 - <b>Reactive React<br/>(by Zahi cohen) </b></p> <p>In this talk we will build a multiplayer app using React, Recompose &amp; Firebase, all connected together by Rx Observables.</p> <p>19:15 - <b>Break </b></p> <p>19:30 -  The mysteries of Observables of Observables...<br/><b>(by Yshay Yaacobi) </b></p> <p>Flattening an Observable is quite common in rx programming, yet choosing the right operator might be challenging...<br/>In this talk, we'll walk through some of these flattening operators that are identical in signature but totally different in behavior.</p> ",
            "visibility": "public"
        },
        {
            "created": 1480879580000,
            "duration": 5400000,
            "id": "236028431",
            "name": "Handle your funds wisely",
            "status": "upcoming",
            "time": 1482165000000,
            "updated": 1481030848000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 29,
            "venue": {
                "id": 24782665,
                "name": "Eliezer Centere (מרכז הצעירים)",
                "lat": 32.02274703979492,
                "lon": 34.77984619140625,
                "repinned": false,
                "address_1": "אליעזר בן יהודה,18, חולון",
                "city": "Holon",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1439197992000,
                "name": "Start Holon",
                "id": 18818419,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "StartHolon",
                "who": "Members"
            },
            "link": "https://www.meetup.com/StartHolon/events/236028431/",
            "description": "<p>Whether if you're bootstrapping, funded by FFFs, angel or a VC.</p> <p><br/>You have funds, and sooner or later you're going to burn them.</p> <p>In order to raise more money and keep your startup above water, you will need to handle your funds wisely, and burn it efficiently.</p> <p>\n\n\nIn our next meetup, we're happy to host Stephan Guberman ,CEO Guberman group.</p> <p>Guberman Group is a well known accounting and finance office in the Israeli startup eco-system, with many years of experience and successful companies.</p> <p>Now it's time to share their experience with StartHolon.</p> <p>\n\n\n<b>Agenda:</b></p> <p>* 18:30 Networking</p> <p>* 19:00 Handle your funds wisely</p> <p>* 20:00 Q&amp;A</p> <p>\n\n\n----------------------------------------------------------------------------</p> <p>בדרך לגיוס מחברים ומשפחה ? בסבב פגישות עם אנג'לים ? עובדים על המצגת לקרנות הון- הסיכון ?</p> <p>בכל אחד מהמקרים הבאים, אתם כנראה עומדים לגלות תחום חדש, שיכול לחרוץ את גורל המיזם שלכם עוד בטרם גייסתם את השקל הראשון.</p> <p>תחום הפיננסים!</p> <p>ולא, אנחנו לא מדברים על הסכום שאותו אתם רוצים לגייס או על הסכום שתקבלו באקזיט , אנו מדברים על ההתנהלות הפיננסים שלכם בדרך לשם..</p> <p>המשקיעים הרציניים יראו בהתנהלות שלכם בטרם לגיוס כמדד להצלחת המיזם בהמשך.</p> <p>אז בכדי לרכז עבורכם את הנושא ולתת לכם כלים ממשיים להתמודדות עם העתיד לבוא,</p> <p>אנו נארח במפגש הבא שלנו את סטפן גוברמן, מנכ\"ל מקבוצת גוברמן אשר מלווה חברות כמו גוגל, פייפאל, איירונסורס ומאות סטארטאפים נוספים.</p> <p>במסגרת הרצאתו בנושא \"התנהלות פיננסית של סטארטאפ בתחילת דרכו\" סטפן ישוחח על הייחוד שבסטארט-אפ וצרכיו החשבונאיים, תיאור מערך הכספים והחלטות קריטיות ראשוניות כמו מתי להתמסד ולהקים חברה </p> <p><b>אג׳נדה:</b></p> <p>18:30 - נטוורקינג</p> <p>19:00 - 20:00 הרצאה</p> <p>\n\n\n<img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/a/e/d/3/600_456584755.jpeg\" /></p> ",
            "visibility": "public"
        },
        {
            "created": 1478466431000,
            "duration": 10800000,
            "id": "fpkffmywcbwb",
            "name": "Scala Course for Java developers",
            "rsvp_limit": 1,
            "status": "upcoming",
            "time": 1482244200000,
            "updated": 1481805263000,
            "utc_offset": 7200000,
            "waitlist_count": 22,
            "yes_rsvp_count": 3,
            "venue": {
                "id": 23685463,
                "name": "Tikal's office",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "repinned": false,
                "address_1": "Kiryat Atidim, building 7, 3rd floor",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel",
                "phone": "03-6488618"
            },
            "group": {
                "created": 1328085870000,
                "name": "Fullstack Developers Israel",
                "id": 3212532,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "full-stack-developer-il",
                "who": "Fullstackers"
            },
            "link": "https://www.meetup.com/full-stack-developer-il/events/235547825/",
            "description": "<p><b>Are you a Java developer who wants to program in Scala?</b></p> <p>In this course you will learn to program in the Scala language by Evyatar Kafkafi from <a href=\"http://www.tikalk.com/hebrew/\">Tikal</a>.</p> <p><b>You will be one of 10 participants</b> (or maybe even less),<br/><b>the course has 5 sessions (each of them 3 hours long), and You MUST participate in all 5 sessions. There is no homework!</b></p> <p><b>** To register you must <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeocDbZZnqQUKH7Wo_gJTNx_ZP2VxrkUT7Qh9WtWiHprdBD0A/viewform\">fill out this form</a>, so we can get back to you to arrange your participation** <br/></b></p> <p>In the first 3 sessions we will study together how to program in Scala. <br/>Then we will have 2 sessions in which we will work on a project that all of us develop together.</p> <p><b>*This Scala course is targeted for experienced Java developers (2 years or more of experience of developing with the Java language).</b></p> <p><br/>You do NOT need to have any prior knowledge of Scala.</p> <p>In the end of the course you will reach a level of:</p> <p>1. programming simple tasks independently, in Scala</p> <p>2. being able to continue learning Scala on your own, from books, videos, and internet resources.</p> <p>3. understand Scala code samples in lectures and presentations on other topics (such as Spark, Akka, etc)</p> <p>\n\n\n<b>Syllabus of the course:</b></p> <p>\u2022 Writing Scala code in a regular Maven project, using the IDE</p> <p>\u2022 Scala classes, methods, object instantiation, constructors, inheritance</p> <p>\u2022 Conditionals and loops</p> <p>\u2022 Types, Operators, syntax of method calls and passing arguments to methods</p> <p>\u2022 Traits</p> <p>\u2022 Companion objects, the apply() method</p> <p>\u2022 Pattern matching</p> <p>\u2022 Case classes</p> <p>\u2022 Tuples</p> <p>\u2022 Collections (Lists, Maps)</p> <p>\u2022  High Order functions</p> <p>\u2022  Filter and map</p> <p>\u2022 Functional Programming</p> <p>\u2022 Other Scala language constructs and idioms</p> ",
            "visibility": "public"
        },
        {
            "created": 1481014973000,
            "id": "236063437",
            "name": "View to BIG DATA and Real time analytics",
            "status": "upcoming",
            "time": 1482246000000,
            "updated": 1481786238000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 82,
            "venue": {
                "id": 24374783,
                "name": "Mindspace",
                "lat": 32.06471252441406,
                "lon": 34.774356842041016,
                "repinned": false,
                "address_1": "Ahad Ha'am 54",
                "city": "tel aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1480962322000,
                "name": "Cutting edge tech and Big Data case studies",
                "id": 21463981,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Cutting-edge-tech-and-Big-Data-case-studies",
                "who": "Members"
            },
            "link": "https://www.meetup.com/Cutting-edge-tech-and-Big-Data-case-studies/events/236063437/",
            "description": "<p><b>Optimal+ and Twingo are happy to invite you to a BIG DATA meetup</b></p> <p><br/>This meetup will deal with BIG DATA DB technologies, each speaker will present a premium BIG DATA solution that works for his company, and you will get better understanding how things are working when you provide a large scale DB solutions together with some valuable tips based on real case studies.</p> <p>This is a very ingesting use case, both companies introduce new technologies (Optimal+ choose Vertica together with Hadoop as their solution, appsflyer choose MEMSql with Spark), and managing a BIG DATA challenge -  come and learn BIG DATA from the best!</p> <p>Agenda:</p> <p>17:00 \u2013 17:30 \u2013 Gathering drinks &amp; food</p> <p>17:30-18:20 - <b>Alon Malki - </b>Chief Architect - Optimal+</p> <p>\"Maximize Hadoop and Vertica big data solution - Ad hoc &amp; Batch analytics on a cost effective Big Data platform\u201d</p> <p>This is the story of how O+ built a cost effective solution on top of Hadoop and Vertica to answer both batch and Ad Hoc requirements while minimizing data duplication and required nodes, bringing a cost effective solution that can be relevant both for big and small customers. O+ big data platform is an OEM solution in PB scale for customers like Qualcomm, Broadcom and nvidia.</p> <p>Five minute break</p> <p>18:25-18:55 - <b>Morri </b><b>Feldman</b><b>- </b><b>Data engineer - AppsFlyer</b></p> <p>Join me on our journey and I will show you the current solution that implements real-time aggregation over MemSQL integrated with the batch processing over Apache Spark. The new architecture solved not only our pains but allowed us to aggregate X10 amount of data with much faster response times, keep up with product demands and it was a cheaper solution from the production cost perspective.</p> <p>We kindly ask -RSVP only if you actually attends to come- there is a 70 person limit</p> ",
            "how_to_find_us": "-1 Floor, Auditorium",
            "visibility": "public"
        },
        {
            "created": 1480584358000,
            "id": "235954109",
            "name": "Investment & Innovation in InsurTech",
            "status": "upcoming",
            "time": 1482249600000,
            "updated": 1482071261000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 65,
            "venue": {
                "id": 24723074,
                "name": "SOSA",
                "lat": 32.05317687988281,
                "lon": 34.77231979370117,
                "repinned": false,
                "address_1": "Shocken 13",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1470911830000,
                "name": "#InsurTech Takeover",
                "id": 20304063,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "InsurTech-Takeover",
                "who": "Members"
            },
            "link": "https://www.meetup.com/InsurTech-Takeover/events/235954109/",
            "description": "<p><i>As part of the first Insurtech Israel Startup Competition, SOSA and JVP together with AXA Strategic Ventures, Kamet, Deloitte, Earnix, HFN and Startup Nation Central are proud to present \"Investment &amp; Innovation in Insurtech.\" </i></p> <p><i>Meet major players in the global insurance industry and gain the practical insights on what challenges they face and the innovations they seek.</i></p> <p><b>When: December 20th, 18:00</b></p> <p><b>Where: SOSA, Shocken 13, Tel Aviv </b></p> <p><b>RSVP:</b> <a href=\"https://www.eventbrite.com/e/investment-innovation-in-insurtech-tickets-29783414996\"><a href=\"https://www.eventbrite.com/e/investment-innovation-in-insurtech-tickets-29783414996\" class=\"linkified\">https://www.eventbrite.com/e/investment-innovation-in-insurtech-tickets-29783414996</a></a></p> <p>\n\n\n<b>Agenda </b></p> <p>- 18:00-18:30 - Gathering.</p> <p>- 18:30-18:40 \u2013 Yonatan Machado, Partner, JVP \u2013 Introduction to the InsurTech Competition.</p> <p>- 18:40-19:05  - Joe Guastella, Head of Deloitte\u2019s Financial Services consulting practice.</p> <p>- 19:05-19:30 \u2013 Shay Simkin \u2013 CEO of Howden Israel</p> <p><b>- 19:30-19:55 \u2013</b><b>Alex Zukerman, VP Product Marketing, Sapiens</b></p> <p>- 19:55-20:00 - Closing</p> <p><b>Joe Guastella</b></p> <p>Joe leads Deloitte\u2019s US Financial Services consulting practice and is a member of the Global Financial Services executive team. He is responsible for service delivery in areas of strategy, operations, human capital, technology and risk services. Joe has more than 25 years' experience guiding financial services execs in the design of strategic change management and large scale transformations. Prior to his global and US leadership roles, he led Deloitte\u2019s Asia Pacific Insurance Consulting practice</p> <p>J<b>Shay Simkin</b></p> <p>Shay Simkin is the Managing Director of Howden Insurance Brokers Israel and Head of Cyber for Howden Global (world's largest employee-owned insurance broker). Shay has more than 25 years of experience in the Insurance Broking industry, serving in senior management roles both in Israel and Europe. Shay is a global expert and pioneer in the Cyber Insurance space. As the founder of InsurTec.com back in 1997, he was one of the first Insurance brokers to introduce Cyber &amp; Technology insurance solutions, by drafting cyberspace and technology insurance policies. As a result, Shay has become a world expert in Cyber Liability insurance and is currently leading Howden group's Cyber Liability initiatives worldwide. </p> <p><br/>More about the Competition: </p> <p><img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/2/f/1/b/600_456492059.jpeg\" /></p> <p>\n\n\n\n\n\n<i><br/></i></p> <p><i><br/></i></p> ",
            "how_to_find_us": "SOSA",
            "visibility": "public"
        },
        {
            "created": 1478090304000,
            "duration": 9000000,
            "id": "235292442",
            "name": "Cassandra and Scylla Real Life Experience by Kenshoo & MyHeritage  ",
            "status": "upcoming",
            "time": 1482336000000,
            "updated": 1479054296000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 117,
            "venue": {
                "id": 4761372,
                "name": "Kenshoo",
                "lat": 32.106529235839844,
                "lon": 34.83524703979492,
                "repinned": false,
                "address_1": "HaBarzel 6",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1456749346000,
                "name": "Tech-Talk-Teach",
                "id": 19641607,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Tech-Talk-Teach",
                "who": "Members"
            },
            "link": "https://www.meetup.com/Tech-Talk-Teach/events/235292442/",
            "manual_attendance_count": 0,
            "description": "<p><b>Agenda: </b><br/>18:00 \u2013 18:30- Gathering (food and drinks)<br/>18:30 \u2013 19:15- Scylla and Cassandra at Kenshoo- Noam Hasson, Big Data Team Leader @ Kneshoo<br/>19:30-20:15- PeopleStore - blazing fast 2.5 billion profiles storage- Ran Peled, Chief Architect @MyHeritage</p> <p>\n\n<b>\"Scylla and Cassandra at Kenshoo\"</b></p> <p><b>Abstract: </b><br/>Kenshoo is the industry leader in digital marketing and has run Cassandra for quite some time now. The Kenshoo team was interested in Scylla not just due to performance but for ease of administration. It is important to be able to run all of the background operations a sophisticated database keeps under the hood. Kenshoo engineer Noam Hasson demonstrates the speed of compaction and repair of Scylla verse Cassandra. Eventually Noam shows that three Scylla VMs can handle the load of 40 physical Cassandra machines.</p> <p><b>Bio: </b><br/>Noam Hasson has over 12 years of web development experience, and is currently the in-house big data expert at Kenshoo, a global software company that is the sole leader in bid management software and social advertising platforms. Previously, Noam was a web developer with StartApp, a global monetization and advertising mobile network. Prior to that, Noam was a co-founder and CEO of SociaLayer.com, an Israel-based software startup focusing on cutting-edge solutions and web technologies. Earlier in his career, Noam was the CTO of Mekusharim, a leading provider of social networking media solutions.</p> <p><b>\"PeopleStore - blazing fast 2.5 billion profiles storage\"</b></p> <p><b>Abstract: </b><br/>MyHeritage is home to 82 million users with 2.5 billion rich personal profiles in their family trees, stored on complex and highly optimized MySQL infrastructure. As we started encountering scalability and performance issues, we have built a new data store, based on Cassandra, Mesos+Docker, and Hadoop, that is highly scalable and blazing fast. In this meetup we will share the architecture, design considerations and lessons learned. Among the complexities we will cover is the challenge to load the system while data is changing, keeping a MySQL source-of-truth and Cassandra in synch, errors handling and monitoring.</p> <p><b>Bio: </b><br/>Ran Peled is Chief Architect at MyHeritage, with over 30 years of software development experience, and expertise in large-scale Internet applications.</p> ",
            "visibility": "public"
        },
        {
            "created": 1481805548000,
            "duration": 10800000,
            "id": "236256569",
            "name": "Innovative Scaling Solutions",
            "status": "upcoming",
            "time": 1482336000000,
            "updated": 1481805548000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 54,
            "venue": {
                "id": 23846222,
                "name": "Bitan 26, Namal Tel Aviv",
                "lat": 0.0,
                "lon": 0.0,
                "repinned": false,
                "address_1": "Yosef Yakutieli 4, Tel Aviv",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1387171943000,
                "name": "Meetups at Wix",
                "id": 11468592,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "at-wix",
                "who": "Members"
            },
            "link": "https://www.meetup.com/at-wix/events/236256569/",
            "description": "<p>Israel has been titled as a start up nation, but new startups worldwide are increasing drastically, and more scaling challenges are introduced. These startups, don\u2019t always remain small, as some grow quickly, struggling to hold on to that innovation mentality. There are also large companies that are trying to learn from startups, how to stay relevant in the field.</p> <p>This meetup will discuss the innovative scaling solutions by AWS and Wix and the culture and technologies to support such solutions. Please note the lectures will be given in Hebrew.</p> <p><b>Schedule:</b></p> <p>18:00 - 18:30 - Drinks and food</p> <p>18:30 - 19:15 - Scaling Wix to over 90M users</p> <p>19:15 - 19:30 - Break</p> <p>19:30 - 20:15 - Scaling Your Business in Amazon Style</p> <p>20:15 - More drinks!</p> <p>\n\n<b>Scaling Wix to over 90M users - Yoav Abrahami<br/></b></p> <p>Over the first 10 years of Wix, Wix infrastructure has gone a number of transformations, starting as a monolithic application server with MySQL, evolving to a service based architecture with with diverse infrastructure. Over this 10 years journey, we have learned a thing or two - some DOs and some DON'Ts.</p> <p>In this presentation I will go over the evolution of Wix architecture, with the different transformations we have done to support Wix at scale. We will share some of our insights about building a web infrastructure for over 90M users</p> <p>Bio: Yoav Abrahami is the Chief Architect at Wix.com, working with developers and operations on building wix future products as well as accelerating and improving development processes. Prior to joining Wix.com, Yoav was an Architect at Amdocs Cramer OSS division. Yoav has a MS in Physics and BS in Computer Science from Tel Aviv University.</p> <p><b>Scaling Your Business in Amazon Style -  Guy Ernest</b></p> <p>In Amazon we are very passionate about helping our customers grow to become the next Amazon, Netflix, IronSource or Waze. We learned so much from our own experience and from the experience of many of our customers, and we love to share this experience with others.</p> <p>We see many small startups that are growing very quickly and struggling to keep the startup (=innovation) mentality. We also see many big companies that are trying to learn from startups how to stay relevant in a competitive market. It is more about agility, independence, smart application, collaboration, and the culture and technologies that can support it.</p> <p>In this lecture, I will share my personal experience and Amazon experience in solving scale problems. Machine learning is one of these scale solutions, and it is also the reason we broken down Amazon to very small two-pizza teams, and the tools that we give to these teams to have superpowers to innovate fast. Bio:</p> <p><br/>Guy Ernest is the Principal Business Development Manager, Machine Learning at AWS. He joined Amazon more than 4 years ago as a solution architect and helped in building the technical team of AWS in Israel. 2 years ago, he moved to Amazon HQ in Seattle to work as a solution architect for Amazon.com, helping one of the largest companies on the planet to use the cloud better. He recently moved to a business development role in one of my passions of machine learning and deep learning, and helping customers to adopt \u201cML first\u201d strategies.He also spent 25 years in various technical roles in the IDF, in his own startups and some big companies.</p> ",
            "how_to_find_us": "Bitan 26 is located across from Japanika",
            "visibility": "public"
        },
        {
            "created": 1460672343000,
            "id": "tqvmslyvqbhc",
            "name": "bicycle workshop",
            "status": "upcoming",
            "time": 1482688800000,
            "updated": 1460672343000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 1,
            "venue": {
                "id": 13933482,
                "name": "TAMI",
                "lat": 32.171016693115234,
                "lon": 34.85884094238281,
                "repinned": false,
                "address_1": "Kibbutz Galuyot 45",
                "address_2": "Studio #106, 3rd Floor ",
                "city": "Tel Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1380728634000,
                "name": "Tel Aviv Makers (TAMI)",
                "id": 10521552,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Tel-Aviv-Makers-TAMI",
                "who": "Hackers"
            },
            "link": "https://www.meetup.com/Tel-Aviv-Makers-TAMI/events/236057642/",
            "description": "<p>We will try to  learn how to fix a bicycle.<br/>You may bring along the bike or a wheel and we can tackle it together.<br/>The idea is to try to rebuild or fix the old parts and re-use them, whenever possible.<br/>There are tools, support and very few parts at the space.</p> ",
            "visibility": "public"
        },
        {
            "created": 1481574498000,
            "id": "236200637",
            "name": "Arduino Programming Techniques #4: On memory, pointers, arrays, and bytes.",
            "status": "upcoming",
            "time": 1482771600000,
            "updated": 1482079065000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 9,
            "venue": {
                "id": 13933482,
                "name": "TAMI",
                "lat": 32.171016693115234,
                "lon": 34.85884094238281,
                "repinned": false,
                "address_1": "Kibbutz Galuyot 45",
                "address_2": "Studio #106, 3rd Floor ",
                "city": "Tel Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1380728634000,
                "name": "Tel Aviv Makers (TAMI)",
                "id": 10521552,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Tel-Aviv-Makers-TAMI",
                "who": "Hackers"
            },
            "link": "https://www.meetup.com/Tel-Aviv-Makers-TAMI/events/236200637/",
            "description": "<p><img src=\"https://a248.e.akamai.net/secure.meetupstatic.com/photos/event/d/e/5/0/600_453776912.jpeg\" /></p> <p>*** Please note that that due to the date change the lecture will takes place at the TAMI hackerspace and not at Campus Tel Aviv (Google) as initially planned.</p> <p>This time we will explore things we can do with memory, pointers, arrays, and memory buffers.</p> <p>We will revisit the run-time environment, and learn about PROGMEM, and EEPROM.</p> <p><br/>We will learn how to manipulate memory buffers, and see where that is useful.</p> <p>We'll explore the strange relations in C/C++ between pointers and arrays, and what does it mean for multidimensional arrays.</p> <p>We will learn about pointer arithmetic, sizeof, memset, memcpy, memmove, strcpy, strncpy.</p> <p>We will learn about placement new, for C++, and also how to create pointer-like classes.</p> <p>We will try to overcome the heap fragmentation problem, which prevents us to use dynamic allocation in routine operations.</p> ",
            "visibility": "public"
        },
        {
            "created": 1478466431000,
            "duration": 10800000,
            "id": "fpkffmyvqbkc",
            "name": "Scala Course for Java developers",
            "rsvp_limit": 1,
            "status": "upcoming",
            "time": 1482849000000,
            "updated": 1481805263000,
            "utc_offset": 7200000,
            "waitlist_count": 1,
            "yes_rsvp_count": 3,
            "venue": {
                "id": 23685463,
                "name": "Tikal's office",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "repinned": false,
                "address_1": "Kiryat Atidim, building 7, 3rd floor",
                "city": "Tel Aviv-Yafo",
                "country": "il",
                "localized_country_name": "Israel",
                "phone": "03-6488618"
            },
            "group": {
                "created": 1328085870000,
                "name": "Fullstack Developers Israel",
                "id": 3212532,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "full-stack-developer-il",
                "who": "Fullstackers"
            },
            "link": "https://www.meetup.com/full-stack-developer-il/events/236287705/",
            "description": "<p><b>Are you a Java developer who wants to program in Scala?</b></p> <p>In this course you will learn to program in the Scala language by Evyatar Kafkafi from <a href=\"http://www.tikalk.com/hebrew/\">Tikal</a>.</p> <p><b>You will be one of 10 participants</b> (or maybe even less),<br/><b>the course has 5 sessions (each of them 3 hours long), and You MUST participate in all 5 sessions. There is no homework!</b></p> <p><b>** To register you must <a href=\"https://docs.google.com/forms/d/e/1FAIpQLSeocDbZZnqQUKH7Wo_gJTNx_ZP2VxrkUT7Qh9WtWiHprdBD0A/viewform\">fill out this form</a>, so we can get back to you to arrange your participation** <br/></b></p> <p>In the first 3 sessions we will study together how to program in Scala. <br/>Then we will have 2 sessions in which we will work on a project that all of us develop together.</p> <p><b>*This Scala course is targeted for experienced Java developers (2 years or more of experience of developing with the Java language).</b></p> <p><br/>You do NOT need to have any prior knowledge of Scala.</p> <p>In the end of the course you will reach a level of:</p> <p>1. programming simple tasks independently, in Scala</p> <p>2. being able to continue learning Scala on your own, from books, videos, and internet resources.</p> <p>3. understand Scala code samples in lectures and presentations on other topics (such as Spark, Akka, etc)</p> <p>\n\n\n<b>Syllabus of the course:</b></p> <p>\u2022 Writing Scala code in a regular Maven project, using the IDE</p> <p>\u2022 Scala classes, methods, object instantiation, constructors, inheritance</p> <p>\u2022 Conditionals and loops</p> <p>\u2022 Types, Operators, syntax of method calls and passing arguments to methods</p> <p>\u2022 Traits</p> <p>\u2022 Companion objects, the apply() method</p> <p>\u2022 Pattern matching</p> <p>\u2022 Case classes</p> <p>\u2022 Tuples</p> <p>\u2022 Collections (Lists, Maps)</p> <p>\u2022  High Order functions</p> <p>\u2022  Filter and map</p> <p>\u2022 Functional Programming</p> <p>\u2022 Other Scala language constructs and idioms</p> ",
            "visibility": "public"
        },
        {
            "created": 1468677615000,
            "id": "232661706",
            "name": "December Lean Startup Event",
            "status": "upcoming",
            "time": 1482942600000,
            "updated": 1479024906000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 56,
            "venue": {
                "id": 21352552,
                "name": "Campus TLV",
                "lat": 32.060001373291016,
                "lon": 34.7599983215332,
                "repinned": false,
                "address_1": "98 Yigal Alon st.",
                "address_2": "Floor 34rd (Electra Tower)",
                "city": "Tel-Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1360946293000,
                "name": "Lean Startup - Tel Aviv",
                "id": 7194012,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "Lean-Startup-Tel-Aviv",
                "who": "Entrepreneurs"
            },
            "link": "https://www.meetup.com/Lean-Startup-Tel-Aviv/events/232661706/",
            "description": "<p>Discuss Product Discovery and Growth Hacking for Startups</p> ",
            "visibility": "public"
        },
        {
            "created": 1480586995000,
            "duration": 7200000,
            "id": "235954471",
            "name": "Co-Founders Speed Dating & Pitching event - by 8200 EISP",
            "status": "upcoming",
            "time": 1482944400000,
            "updated": 1481322743000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 204,
            "venue": {
                "id": 21352552,
                "name": "Campus TLV",
                "lat": 32.060001373291016,
                "lon": 34.7599983215332,
                "repinned": false,
                "address_1": "98 Yigal Alon st.",
                "address_2": "Floor 34rd (Electra Tower)",
                "city": "Tel-Aviv",
                "country": "il",
                "localized_country_name": "Israel"
            },
            "group": {
                "created": 1351416612000,
                "name": "8200 EISP - Entrepreneurship and Innovation Support Program",
                "id": 5592412,
                "join_mode": "open",
                "lat": 32.06999969482422,
                "lon": 34.77000045776367,
                "urlname": "8200-EISP",
                "who": "Entrepreneurs"
            },
            "link": "https://www.meetup.com/8200-EISP/events/235954471/",
            "description": "<p><img src=\"http://photos3.meetupstatic.com/photos/event/e/8/4/e/600_456719470.jpeg\" /></p> <p>** PLEASE NOTE: The talk will be held in Hebrew **</p> <p><br/>If you are looking for co-founders or connections in general; if you want to pitch your start-up/product/service/skills/etc. or if you just want to come and watch an entertaining, rapid-fire event, then this is THE one to attend.</p> <p>** The event is hosted by the 8200 EISP accelerator. The event is being sponsored by Maverick Ventures.</p> <p>So, who should register? Only if you are -</p> <p>- An entrepreneur with an idea that is looking for a co-founder; fill in your start-up and description here: <a href=\"https://goo.gl/forms/Q40YCnkWcmM5Tiii1\"><a href=\"https://goo.gl/forms/Q40YCnkWcmM5Tiii1\" class=\"linkified\">https://goo.gl/forms/Q40YCnkWcmM5Tiii1</a></a></p> <p>- Entrepreneurs at heart that are looking for a start-up to join.</p> <p>AGENDA:</p> <p>19:00-pm \u2013 Get together, snacks and drinks</p> <p>19:30-pm \u2013 Few words from the organizers</p> <p>19:40-pm - STRICTLY '60 second' speed pitching*</p> <p>20:45-pm - 'Dating' and socializing</p> <p><br/>*Suggested breakdown for 60-second pitches (Remember: practice makes perfect!): </p> <p>20s - Who you are. </p> <p>20s - What you do/are working on. </p> <p>20s - Who/what you are looking for.</p> <p>This event is free!</p> <p>\n\n\n**Event Sponsor: Maverick Ventures</p> <p>Maverick Ventures is a boutique venture capital fund based in Tel Aviv focusing on growth stage Israel-related technology ventures. The fund has made 12 investments in the last year and a half, investing on average between $1-3 Million dollars in companies with existing proven traction. The fund is run by former entrepreneurs with a track record and is backed solely by hand-picked private strategic investors from around the world, whom are proactively helpful in growth through their own networks. For more information please visit &lt;a&gt;www.maverick.vc.&lt;/a&gt;</p> <p>**8200 EISP</p> <p>8200 EISP was the first start-up accelerator in Israel, founded in late 2011. Our vision is to harness the vast network of 8200 alumni in order to promote early stage, first-time entrepreneurs from all industries. This is our way as alumni of 8200 to give back to the Israeli society.</p> <p><br/>80% of the program alumni are currently leading their start-up as founders. Our alumni raised seed funding and beyond of over $400M in total and employ more than 450 people in Israel and overseas.</p> <p><br/><a href=\"http://www.eisp.org.il/en/home\"><a href=\"http://www.eisp.org.il/en/home\" class=\"linkified\">http://www.eisp.org.il/en/home</a></a> is funded and supported by our partners, all leaders in their respective fields. Our partners include Bank Hapoalim (the largest bank in Israel), EY Israel, law firms Naschitz Brandes Amir and Pearl Cohen Zedek Latzer Baratz, the BRM Group, Star Farm Ventures, Battery Ventures, AOL Israel, Nextage, Matrix (8300), Elron and WeWork Israel.</p> <p><br/>Follow us:</p> <p>Facebook - תוכנית היזמות של יוצאי 8200 - EISP</p> <p>Meetup - <a href=\"http://www.meetup.com/8200-EISP/\"><a href=\"http://www.meetup.com/8200-EISP/\" class=\"linkified\">http://www.meetup.com/8200-EISP/</a></a></p> ",
            "visibility": "public"
        }
    ]
}